[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 10
# Define
schemes,
  everforest_dark_hard: &everforest_dark_hard
    primary:
      background: '#272e33'
      foreground: '#d3c6aa'
    normal:
      black:   '#414b50'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_medium: &everforest_dark_medium
    primary:
      background: '#2d353b'
      foreground: '#d3c6aa'
    normal:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#475258'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_dark_soft: &everforest_dark_soft
    primary:
      background: '#333c43'
      foreground: '#d3c6aa'
    normal:
      black:   '#4d5960'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
    bright:
      black:   '#4d5960'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
  everforest_light_hard: &everforest_light_hard
    primary:
      background: '#fffbef'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e8e5d5'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e8e5d5'
  everforest_light_medium: &everforest_light_medium
    primary:
      background: '#fdf6e3'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e0dcc7'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#e0dcc7'
  everforest_light_soft: &everforest_light_soft
    primary:
      background: '#f3ead3'
      foreground: '#5c6a72'
    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#d8d3ba'
    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#d8d3ba'

# Apply
colors: *everforest_dark_medium